# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
